cc_library(
    name = "longest_substring_without_repeating_characters",
    srcs = ["longest_substring_without_repeating_characters.cc"],
    hdrs = ["longest_substring_without_repeating_characters.h"],
)

cc_test(
    name = "longest_substring_without_repeating_characters_test",
    srcs = ["longest_substring_without_repeating_characters_test.cc"],
    deps = [
        ":longest_substring_without_repeating_characters",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
