cc_library(
    name = "longest_substring_without_repeating_characters",
    srcs = ["longest_substring_without_repeating_characters.cc"],
    hdrs = ["longest_substring_without_repeating_characters.h"],
)

cc_test(
    name = "longest_substring_without_repeating_characters_test",
    srcs = ["longest_substring_without_repeating_characters_test.cc"],
    deps = [
        ":longest_substring_without_repeating_characters",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "integer_to_roman",
    srcs = ["integer_to_roman.cc"],
    hdrs = ["integer_to_roman.h"],
)

cc_test(
    name = "integer_to_roman_test",
    srcs = ["integer_to_roman_test.cc"],
    deps = [
        ":integer_to_roman",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "roman_to_integer",
    srcs = ["roman_to_integer.cc"],
    hdrs = ["roman_to_integer.h"],
)

cc_test(
    name = "roman_to_integer_test",
    srcs = ["roman_to_integer_test.cc"],
    deps = [
        ":roman_to_integer",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
